const formulaDefinitions = {
  revenue_total: {
    title: 'Gesamtumsatz / Total Revenue',
    formula: 'Umsatz = SUM(revenue_eur) — Spalte "revenue_eur" aus Rechnungsdaten',
    dataSource: 'File: dashboard_data.json → annual_summary[].revenue_eur\nFile: sales_transactions.json → recent_invoices[].revenue_eur\nFields: revenue_eur (Umsatz EUR), invoices (Rechnungen), unique_customers (Kunden)',
    methodology: 'Summed from annual_summary array in dashboard_data.json, column "revenue_eur". Cross-verified against individual invoice line items in sales_transactions.json. Each year\'s Umsatz (revenue_eur) is an independent sum.',
    confidence: 'verified',
    lastUpdated: '2024-12-31',
  },
  revenue_by_year: {
    title: 'Revenue by Year',
    formula: 'Revenue(year) = annual_summary[year].revenue_eur',
    dataSource: 'File: dashboard_data.json → annual_summary[]\nFields: Year, revenue_eur, invoices, unique_customers',
    methodology: 'Each year\'s revenue is read directly from dashboard_data.json → annual_summary array. Values for 2022-2025 are pre-aggregated from ERP invoice exports.',
    confidence: 'verified',
    lastUpdated: '2024-12-31',
  },
  db1_margin: {
    title: 'DB I Margin %',
    formula: 'DB I Margin = (Revenue - HKvar) / Revenue × 100',
    dataSource: 'File: products.json → products[].margin_20XX (per year)\nFile: monthly_detail.json → db1_margin per month',
    methodology: 'Deckungsbeitrag I from products.json per-article margins. Monthly breakdown from monthly_detail.json. HKvar = Material + FEK (direct labor).',
    confidence: 'verified',
    lastUpdated: '2024-12-31',
  },
  db2_margin: {
    title: 'Deckungsbeitrag II / DB II Margin %',
    formula: 'DB II = (Umsatz - HKvoll) / Umsatz × 100\nHKvoll = Material + FEK + Fremdleistung + Gemeinkosten',
    dataSource: 'File: dashboard_data.json → annual_summary[].avg_db2_margin\nFile: products.json → products[].margin_20XX (Spalte: margin_2022 bis margin_2025)\nFile: monthly_detail.json → db2_margin (Spalte: db2_margin pro Monat)',
    methodology: 'Deckungsbeitrag II aus dashboard_data.json Spalte "avg_db2_margin". Pro Artikel aus products.json Spalten "margin_2022" bis "margin_2025". HKvoll = Material + Fertigungseinzelkosten (FEK) + Fremdleistung + Fertigungsgemeinkosten (FV).',
    confidence: 'verified',
    lastUpdated: '2024-12-31',
  },
  hkvar_total: {
    title: 'Variable Manufacturing Cost (HKvar)',
    formula: 'HKvar = Material Cost + Direct Labor (FEK)',
    dataSource: 'File: cogs_detail.json → cost_breakdown.material_eur + cost_breakdown.labor_eur\nFile: products.json → products[].material_pct, fek_pct',
    methodology: 'Variable cost components from cogs_detail.json cost_breakdown object. Per-unit percentages from products.json material_pct and fek_pct fields.',
    confidence: 'verified',
    lastUpdated: '2024-12-31',
  },
  hkvoll_total: {
    title: 'Herstellkosten Voll / HKvoll',
    formula: 'HKvoll = Materialkosten + FEK + Fremdleistung + Gemeinkosten (FV)',
    dataSource: 'File: cogs_detail.json → cost_breakdown.total_cogs_eur (Spalte: total_cogs_eur = €8,697,037)\nFile: products.json → products[].hkvoll_per_unit (Spalte: HKvoll pro Stueck)\nFile: inventory_detail.json → cost_trends[].hkvoll_2022 bis hkvoll_2025',
    methodology: 'Herstellkosten Voll aus cogs_detail.json Spalte "total_cogs_eur". Pro Stueck aus products.json Spalte "hkvoll_per_unit". Historischer Trend aus inventory_detail.json Spalten "hkvoll_2022" bis "hkvoll_2025".',
    confidence: 'verified',
    lastUpdated: '2024-12-31',
  },
  fek_total: {
    title: 'Direct Labor Cost (FEK)',
    formula: 'FEK = products[].fek_pct × HKvoll',
    dataSource: 'File: products.json → products[].fek_pct\nFile: cogs_detail.json → cost_breakdown.labor_eur',
    methodology: 'Direct labor percentage from products.json fek_pct field. Absolute value from cogs_detail.json labor_eur in cost_breakdown.',
    confidence: 'verified',
    lastUpdated: '2024-12-31',
  },
  fv_total: {
    title: 'Manufacturing Overhead (FV)',
    formula: 'FV = products[].fv_pct × HKvoll',
    dataSource: 'File: products.json → products[].fv_pct\nFile: cogs_detail.json → cost_breakdown.overhead_eur',
    methodology: 'Overhead percentage from products.json fv_pct field. Absolute overhead from cogs_detail.json overhead_eur in cost_breakdown.',
    confidence: 'verified',
    lastUpdated: '2024-12-31',
  },
  material_cost_ratio: {
    title: 'Material Cost Ratio',
    formula: 'Material % = cost_breakdown.material_eur / cost_breakdown.total_cogs_eur × 100',
    dataSource: 'File: cogs_detail.json → cost_breakdown.material_pct\nFile: cogs_detail.json → cost_by_commodity[].material_pct',
    methodology: 'Material share directly from cogs_detail.json cost_breakdown.material_pct field. Per-commodity breakdown from cost_by_commodity array.',
    confidence: 'verified',
    lastUpdated: '2024-12-31',
  },
  win_rate: {
    title: 'Angebotsquote / Win Rate',
    formula: 'Angebotsquote = Gewonnen / Gesamt × 100\n= quote_summary.won / quote_summary.total_quotes',
    dataSource: 'File: dashboard_data.json → quote_summary\nFields: total_quotes (4.539 Angebote), won (1.684 gewonnen), lost (2.855 verloren), win_rate (0,371)',
    methodology: 'Angebotsquote aus dashboard_data.json Spalte "win_rate" im Objekt "quote_summary". Verifiziert: 1.684 / 4.539 = 37,1%. Pipeline-Stufen in pipeline.json als Gegenprobe.',
    confidence: 'verified',
    lastUpdated: '2024-12-31',
  },
  quote_total: {
    title: 'Total Quotes',
    formula: 'Total = quote_summary.total_quotes',
    dataSource: 'File: dashboard_data.json → quote_summary.total_quotes (4,539)\nFile: pipeline.json → pipeline_stages[].count',
    methodology: 'Total quote count from dashboard_data.json. Pipeline stage breakdown in pipeline.json. Sum of Won + Lost = 1,684 + 2,855 = 4,539.',
    confidence: 'verified',
    lastUpdated: '2024-12-31',
  },
  quote_won: {
    title: 'Won Quotes',
    formula: 'Won = quote_summary.won',
    dataSource: 'File: dashboard_data.json → quote_summary.won (1,684)\nFile: pipeline.json → pipeline_stages[stage="Won"].count',
    methodology: 'Won count from dashboard_data.json and pipeline.json. Cross-verified between both files.',
    confidence: 'verified',
    lastUpdated: '2024-12-31',
  },
  quote_lost: {
    title: 'Lost Quotes',
    formula: 'Lost = quote_summary.lost',
    dataSource: 'File: dashboard_data.json → quote_summary.lost (2,855)\nFile: pricing_analysis.json → rejection_codes[]',
    methodology: 'Lost count from dashboard_data.json. Rejection reasons from pricing_analysis.json rejection_codes array (PA, PR, KN, KE, LZ, TE codes).',
    confidence: 'verified',
    lastUpdated: '2024-12-31',
  },
  avg_conversion_days: {
    title: 'Avg. Conversion Days',
    formula: 'Avg Days = pipeline.avg_days_in_pipeline',
    dataSource: 'File: pipeline.json → avg_days_in_pipeline (53 days)\nFile: price_governance.json → conversion_timing',
    methodology: 'Average pipeline duration from pipeline.json. Conversion timing details from price_governance.json conversion_timing object.',
    confidence: 'verified',
    lastUpdated: '2024-12-31',
  },
  customer_count: {
    title: 'Aktive Kunden / Active Customers',
    formula: 'Kunden = SUM(segments[].count) = 967',
    dataSource: 'File: customers_detail.json → customers[] (967 Kundendaten)\nFile: customers_detail.json → segments[].count (Gesamt: 967)\nFields: customer_id, name, segment, total_revenue_eur, risk_tier, risk_score',
    methodology: 'Kundenanzahl aus customers_detail.json — alle 967 Kunden mit Rechnungsdaten. 4 Segmente: Enterprise, Mid-Market, SME, Occasional.',
    confidence: 'verified',
    lastUpdated: '2024-12-31',
  },
  customer_segments: {
    title: 'Kundensegmente / Customer Segments',
    formula: 'Segment = customers_detail.segments[].segment',
    dataSource: 'File: customers_detail.json → segments[]\nSegments: Enterprise (49), Mid-Market (145), SME (387), Occasional (386)\nFields: segment, count, total_revenue, avg_margin',
    methodology: 'Kundensegmentierung aus customers_detail.json. 4 Segmente nach Umsatzrang: Top 5% Enterprise, 5–20% Mid-Market, 20–60% SME, 60–100% Occasional.',
    confidence: 'verified',
    lastUpdated: '2024-12-31',
  },
  risk_score_avg: {
    title: 'Average Risk Score',
    formula: 'Risk Score = weighted(recency, frequency, monetary, margin_trend)',
    dataSource: 'File: dashboard_data.json → risk_distribution[].avg_score\nFile: customers_detail.json → customers[].risk_score\nFile: ml_analytics.json → churn_prediction.at_risk_customers[]',
    methodology: 'Risk scores from ML churn model in ml_analytics.json. Aggregated into tiers in dashboard_data.json risk_distribution. Per-customer scores in customers_detail.json. Note: ML-derived — will be refined in Phase 5.',
    confidence: 'derived',
    lastUpdated: '2024-12-31',
  },
  risk_distribution: {
    title: 'Risk Distribution',
    formula: 'Tier = LOW (<0.3), MEDIUM (<0.6), HIGH (<0.8), CRITICAL (≥0.8)',
    dataSource: 'File: dashboard_data.json → risk_distribution[]\nTiers: Low (33), Medium (63), High (65), Critical (22) = 183 total',
    methodology: 'Customer risk tiers from dashboard_data.json. Thresholds calibrated on 2022-2024 churn data. Note: ML-derived — thresholds will be refined in Phase 5.',
    confidence: 'derived',
    lastUpdated: '2024-12-31',
  },
  product_count: {
    title: 'Active Products',
    formula: 'Active SKUs = products.summary.total_active_skus',
    dataSource: 'File: products.json → summary.total_active_skus (1,798)\nFile: products.json → products[] (44 sample articles)',
    methodology: 'Full catalog count from products.json summary object. Dashboard shows 44 representative sample products with complete data across 9 Warengruppen.',
    confidence: 'verified',
    lastUpdated: '2024-12-31',
  },
  top_products_revenue: {
    title: 'Top Products by Revenue',
    formula: 'Rank by products[].total_revenue DESC',
    dataSource: 'File: products.json → products[].total_revenue, article_id, description\nFile: products.json → products[].commodity_group',
    methodology: 'Products sorted by total_revenue field from products.json. Each product has revenue broken down by year (revenue_2022 through revenue_2025).',
    confidence: 'verified',
    lastUpdated: '2024-12-31',
  },
  commodity_group_revenue: {
    title: 'Commodity Group Revenue',
    formula: 'Revenue(WG) = commodity_group_revenue[].revenue_eur',
    dataSource: 'File: dashboard_data.json → commodity_group_revenue[]\nFields: commodity_group, revenue_eur, invoices, avg_db2_margin',
    methodology: 'Pre-aggregated revenue by Warengruppe from dashboard_data.json. 9 commodity groups from BKAES to OFRLMG.',
    confidence: 'verified',
    lastUpdated: '2024-12-31',
  },
  commodity_group_margin: {
    title: 'Commodity Group Margin',
    formula: 'Margin(WG) = commodity_group_revenue[].avg_db2_margin',
    dataSource: 'File: dashboard_data.json → commodity_group_revenue[].avg_db2_margin\nFile: cogs_detail.json → cost_by_commodity[].material_pct, labor_pct',
    methodology: 'Average DB II margin per commodity group from dashboard_data.json. Cost structure breakdown from cogs_detail.json cost_by_commodity array.',
    confidence: 'verified',
    lastUpdated: '2024-12-31',
  },
  price_cost_gap: {
    title: 'Price-Cost Gap',
    formula: 'Gap = gap_analysis.by_year[].avg_quoted_margin - avg_actual_margin',
    dataSource: 'File: pricing_analysis.json → gap_analysis.by_year[]\nFile: pricing_analysis.json → gap_analysis.overall (mean_gap: 5.4%)',
    methodology: 'Year-over-year gap between quoted and actual margins from pricing_analysis.json. 2022: 4.2pp, 2023: 5.8pp, 2024: 5.6pp, 2025: 5.5pp. Note: gap values are estimated — will be refined in Phase 5.',
    confidence: 'derived',
    lastUpdated: '2024-12-31',
  },
  yoy_price_change: {
    title: 'Year-over-Year Price Change',
    formula: 'YoY = (revenue_Y / units_Y) / (revenue_Y-1 / units_Y-1) - 1',
    dataSource: 'File: products.json → products[].revenue_20XX, units_20XX\nFile: inventory_detail.json → cost_trends[].cost_change_pct',
    methodology: 'Calculated from per-article revenue and units in products.json. Cost change trends from inventory_detail.json cost_trends.',
    confidence: 'verified',
    lastUpdated: '2024-12-31',
  },
  churn_probability: {
    title: 'Churn Probability',
    formula: 'P(churn) = churn_prediction.at_risk_customers[].churn_probability',
    dataSource: 'File: ml_analytics.json → churn_prediction.total_at_risk (710)\nFile: ml_analytics.json → churn_prediction.at_risk_customers[].churn_probability\nFile: ml_analytics.json → churn_prediction.revenue_at_risk_eur',
    methodology: 'ML churn model output from ml_analytics.json. 710 at-risk customers identified across 967 total. Probabilities range 0.15 to 0.97. Note: ML forecast — accuracy improves with model retraining.',
    confidence: 'forecast',
    lastUpdated: '2024-12-31',
  },
  forecast_revenue: {
    title: 'Revenue Forecast',
    formula: 'Forecast = forecasting.margin_forecast[].p50_margin',
    dataSource: 'File: forecasting.json → margin_forecast[]\nFile: forecasting.json → model_accuracy[]\nFile: forecasting.json → commodity_forecasts[]',
    methodology: 'Ensemble model forecast from forecasting.json. Model accuracy metrics in model_accuracy array. Commodity-level breakdown in commodity_forecasts. Note: ML forecast — will be recalibrated in Phase 6.',
    confidence: 'forecast',
    lastUpdated: '2024-12-31',
  },
  forecast_margin: {
    title: 'Margin Forecast',
    formula: 'Margin = forecasting.margin_forecast[].p50_margin',
    dataSource: 'File: forecasting.json → margin_forecast[].p50_margin\nFile: forecasting.json → margin_forecast[].p10_margin, p90_margin',
    methodology: 'Margin forecast with P10/P50/P90 bands from forecasting.json margin_forecast array. Monthly projections for H1 2026. Note: ML forecast — confidence bands narrow with Phase 6 refinement.',
    confidence: 'forecast',
    lastUpdated: '2024-12-31',
  },
  monte_carlo_range: {
    title: 'Monte Carlo Confidence Range',
    formula: 'P10/P90 = forecasting.monte_carlo.p10, p90',
    dataSource: 'File: forecasting.json → monte_carlo.p10_revenue, p50_revenue, p90_revenue\nFile: forecasting.json → monte_carlo.simulations (10,000)',
    methodology: '10,000 Monte Carlo simulations from forecasting.json. P10 = conservative (€5.8M), P50 = best estimate (€6.3M), P90 = optimistic (€6.9M). Note: simulation — recalibrated each phase.',
    confidence: 'forecast',
    lastUpdated: '2024-12-31',
  },
  margin_trend: {
    title: 'Margin Trend',
    formula: 'Trend = dashboard_data.margin_trend[].margin',
    dataSource: 'File: dashboard_data.json → margin_trend[]\nFields: month, margin, quarterly_avg (48 months: Jan 2022 - Dec 2025)',
    methodology: 'Monthly DB II margin trend from dashboard_data.json. 48 data points across 4 years with quarterly moving average overlay.',
    confidence: 'verified',
    lastUpdated: '2024-12-31',
  },
  monthly_revenue: {
    title: 'Monthly Revenue',
    formula: 'Monthly = dashboard_data.monthly_revenue[].revenue_eur',
    dataSource: 'File: dashboard_data.json → monthly_revenue[]\nFields: Year, Month, month_label, revenue_eur, invoices, avg_db2_margin',
    methodology: 'Monthly revenue breakdown from dashboard_data.json. 48 months of data (2022-2025) with invoice counts and margin per month.',
    confidence: 'verified',
    lastUpdated: '2024-12-31',
  },
  pipeline_stages: {
    title: 'Pipeline Stages',
    formula: 'Stages = pipeline.pipeline_stages[]',
    dataSource: 'File: pipeline.json → pipeline_stages[]\nStages: New Quote (312), Under Review (245), Quoted (567), Negotiation (189), Won (1,684), Lost (2,855)',
    methodology: 'Quote pipeline from pipeline.json. 6 stages with count and EUR value. Conversion funnel rates between stages also available.',
    confidence: 'verified',
    lastUpdated: '2024-12-31',
  },
  top_customers: {
    title: 'Top Customers',
    formula: 'Rank by customers[].total_revenue_eur DESC',
    dataSource: 'File: dashboard_data.json → top_customers[]\nFile: customers_detail.json → customers[].total_revenue_eur, risk_tier, segment',
    methodology: 'Top 20 customers from dashboard_data.json ranked by revenue. Full customer details in customers_detail.json including risk scores and LTV estimates.',
    confidence: 'verified',
    lastUpdated: '2024-12-31',
  },
  rejection_codes: {
    title: 'Rejection Code Analysis',
    formula: 'Codes = pricing_analysis.rejection_codes[]',
    dataSource: 'File: pricing_analysis.json → rejection_codes[]\nCodes: PA (Competitor), PR (Price), KN (No response), KE (Cancelled), LZ (Lead time), TE (Technical)',
    methodology: 'Quote rejection reasons from pricing_analysis.json. 7 rejection codes with counts, lost revenue, and percentage of total lost. Note: Code classification is derived from free-text rejection notes.',
    confidence: 'derived',
    lastUpdated: '2024-12-31',
  },
  win_rate_by_margin: {
    title: 'Win Rate by Margin Band',
    formula: 'WinRate(band) = pricing_analysis.win_rate_by_margin_band[]',
    dataSource: 'File: pricing_analysis.json → win_rate_by_margin_band[]\nBands: <50%, 50-60%, 60-70%, 70-80%, >80%',
    methodology: 'Win rates segmented by quoted margin bands from pricing_analysis.json. Shows inverse relationship: higher margins → lower win rates.',
    confidence: 'verified',
    lastUpdated: '2024-12-31',
  },
  cost_breakdown: {
    title: 'COGS Breakdown',
    formula: 'COGS = cogs_detail.cost_breakdown',
    dataSource: 'File: cogs_detail.json → cost_breakdown\nFields: total_cogs_eur (€8.7M), material_eur, labor_eur, outsourcing_eur, overhead_eur',
    methodology: 'Total COGS and component breakdown from cogs_detail.json. Material 32%, Labor 42%, Outsourcing 18%, Overhead 8%.',
    confidence: 'verified',
    lastUpdated: '2024-12-31',
  },
  cost_by_year: {
    title: 'Annual Cost Trend',
    formula: 'Annual = cogs_detail.cost_by_year[]',
    dataSource: 'File: cogs_detail.json → cost_by_year[]\nFields: year, total_cogs, material, labor, outsourcing, overhead (2022-2025)',
    methodology: 'Year-over-year cost data from cogs_detail.json. 4 years of annual totals with component breakdown.',
    confidence: 'verified',
    lastUpdated: '2024-12-31',
  },
  cost_quarterly: {
    title: 'Quarterly Cost Trend',
    formula: 'Quarterly = cogs_detail.cost_trend_quarterly[]',
    dataSource: 'File: cogs_detail.json → cost_trend_quarterly[]\nFields: year, quarter, total_cost, material, labor, outsourcing, overhead (16 quarters)',
    methodology: '16 quarters of cost data from cogs_detail.json. Quarterly sums verified against annual totals.',
    confidence: 'verified',
    lastUpdated: '2024-12-31',
  },
  cost_by_commodity: {
    title: 'Cost by Commodity Group',
    formula: 'Commodity = cogs_detail.cost_by_commodity[]',
    dataSource: 'File: cogs_detail.json → cost_by_commodity[]\nFields: commodity_group, avg_hkvoll, material_pct, labor_pct, outsourcing_pct, overhead_pct',
    methodology: 'Per-commodity cost structure from cogs_detail.json. 9 commodity groups with HKvoll and cost component percentages.',
    confidence: 'verified',
    lastUpdated: '2024-12-31',
  },
  inventory_cost_trends: {
    title: 'Inventory Cost Trends',
    formula: 'Trends = inventory_detail.cost_trends[]',
    dataSource: 'File: inventory_detail.json → cost_trends[]\nFields: article_id, hkvoll_2022-2025, cost_change_pct, material_share, labor_share',
    methodology: 'Per-article cost trends from inventory_detail.json. Shows HKvoll evolution and cost change percentages over 4 years.',
    confidence: 'verified',
    lastUpdated: '2024-12-31',
  },
  governance_rules: {
    title: 'Price Governance Rules',
    formula: 'Rules = price_governance.price_rules[]',
    dataSource: 'File: price_governance.json → price_rules[]\nFile: price_governance.json → price_history[]\nFile: price_governance.json → conversion_timing',
    methodology: 'Governance rules, price change history, and conversion timing from price_governance.json. Note: rule compliance status is derived from current margin data.',
    confidence: 'derived',
    lastUpdated: '2024-12-31',
  },
  bcg_matrix: {
    title: 'BCG Portfolio Matrix',
    formula: 'Quadrant = ml_analytics.bcg_matrix[].quadrant',
    dataSource: 'File: ml_analytics.json → bcg_matrix[]\nFields: commodity_group, quadrant, growth, margin, revenue',
    methodology: 'BCG classification from ml_analytics.json. Commodity groups placed in Stars/Cash Cows/Question Marks/Dogs based on growth rate and margin. Note: ML-derived classification.',
    confidence: 'derived',
    lastUpdated: '2024-12-31',
  },
  margin_classification: {
    title: 'Margin Classification',
    formula: 'Class = ml_analytics.margin_classification',
    dataSource: 'File: ml_analytics.json → margin_classification\nFields: total_classified, above_target, at_risk, below_floor',
    methodology: 'ML-based margin classification from ml_analytics.json. Products categorized as above target, at-risk, or below floor based on DB II margin thresholds.',
    confidence: 'derived',
    lastUpdated: '2024-12-31',
  },
  anomaly_detection: {
    title: 'Anomaly Detection',
    formula: 'Anomalies = ml_analytics.anomaly_detection',
    dataSource: 'File: ml_analytics.json → anomaly_detection\nFields: total_anomalies, margin_anomalies, revenue_anomalies',
    methodology: 'Statistical anomaly detection from ml_analytics.json. Identifies unusual margin or revenue patterns that deviate significantly from historical norms.',
    confidence: 'derived',
    lastUpdated: '2024-12-31',
  },
  churn_summary: {
    title: 'Customer Churn Summary',
    formula: 'Churn = customers_detail.churn_summary[]',
    dataSource: 'File: customers_detail.json → churn_summary[]\nFile: ml_analytics.json → churn_prediction',
    methodology: 'Churn risk summary from customers_detail.json with LTV at risk. Detailed predictions from ml_analytics.json churn_prediction.',
    confidence: 'forecast',
    lastUpdated: '2024-12-31',
  },
  price_sensitivity: {
    title: 'Price Sensitivity',
    formula: 'Sensitivity = pricing_analysis.price_sensitivity',
    dataSource: 'File: pricing_analysis.json → price_sensitivity\nFields: won_avg_margin (73.7%), lost_avg_margin (78.9%), margin_diff (5.2pp)',
    methodology: 'Comparison of average margins between won and lost quotes from pricing_analysis.json. Statistically significant (p=0.011): higher-margin quotes are less likely to win.',
    confidence: 'verified',
    lastUpdated: '2024-12-31',
  },
  seasonal_pattern: {
    title: 'Seasonal Pattern',
    formula: 'Seasonal = forecasting.seasonal_indices[]',
    dataSource: 'File: forecasting.json → seasonal_indices[]\nFields: month, index (Jan-Dec)',
    methodology: 'Monthly seasonal indices from forecasting.json. Values >1 indicate above-average months. Used for seasonal adjustment in forecasting models.',
    confidence: 'derived',
    lastUpdated: '2024-12-31',
  },
  model_accuracy: {
    title: 'Forecast Model Accuracy',
    formula: 'Accuracy = forecasting.model_accuracy[]',
    dataSource: 'File: forecasting.json → model_accuracy[]\nModels: arima, prophet, xgboost, ensemble (MAE, RMSE, R²)',
    methodology: 'Model performance metrics from forecasting.json. Ensemble model selected as best performer. Note: accuracy metrics are from backtesting — will be updated with live data in Phase 6.',
    confidence: 'forecast',
    lastUpdated: '2024-12-31',
  },
};

export default formulaDefinitions;
